spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boatsched?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: password

jwt:
  secret: mySecretKeyForBoatSchedJWTTokenGenerationPleaseChangeInProduction

firebase:
  config-path: ""
